/* DO NOT EDIT THIS FILE - it is machine generated */
#include <jni.h>
/* Header for class br_com_jnihello_main_Main */

#ifndef _Included_br_com_jnihello_main_Main
#define _Included_br_com_jnihello_main_Main
#ifdef __cplusplus
extern "C" {
#endif
/*
 * Class:     br_com_jnihello_main_Main
 * Method:    dizerOla
 * Signature: ()V
 */
JNIEXPORT void JNICALL Java_br_com_jnihello_main_Main_dizerOla
  (JNIEnv *, jobject);

#ifdef __cplusplus
}
#endif
#endif
